if (!isserver) exitwith {};

waitUntil {acpl_fncs_initied};

acpl_config_buildings_inited = false;
publicvariable "acpl_config_buildings_inited";

acpl_config_notabuilding = [
	"Land_Razorwire_F",
	"Land_BagFence_Corner_F",
	"Land_BagFence_End_F",
	"Land_BagFence_Long_F",
	"Land_BagFence_Round_F",
	"Land_BagFence_Short_F",
	"Land_Terrace_K_1_EP1",
	"Land_WoodPile_F",
	"Land_Barricade_01_10m_F",
	"Land_Barricade_01_4m_F",
	"Land_Garbage_square3_F",
	"Land_Garbage_square5_F",
	"Land_GarbageBags_F",
	"Land_Garbage_line_F",
	"Land_GarbageBarrel_01_english_F",
	"Land_GarbageBarrel_01_F",
	"Land_GarbagePallet_F",
	"Land_GarbageWashingMachine_F",
	"Land_LuggageHeap_03_F",
	"Land_LuggageHeap_01_F",
	"Land_LuggageHeap_02_F",
	"Land_LuggageHeap_02_F",
	"Land_LuggageHeap_05_F",
	"Land_LuggageHeap_04_F",
	"Oil_Spill_F",
	"Land_GarbageHeap_01_F",
	"Land_GarbageHeap_02_F",
	"Land_GarbageHeap_03_F",
	"Land_GarbageHeap_04_F",
	"Land_JunkPile_F",
	"Land_Tyre_F",
	"Land_Tyre_01_F",
	"Land_Tyre_01_line_x5_F",
	"Land_Tyres_F",
	"Land_GarbageBin_01_F",
	"Land_GarbageContainer_closed_F",
	"Land_GarbageContainer_open_F",
	"Tire_Van_02_F",
	"Tire_Van_02_Cargo_F",
	"Tire_Van_02_Transport_F",
	"Tire_Van_02_Spare_F",
	"Land_WheelieBin_01_F",
	"Land_Kontejner",
	"Land_Kontejner_sklo",
	"Land_Kontejner_papir",
	"Land_Kontejner_plasty",
	"Land_Misc_Garb_Heap_EP1",
	"Garbage_can",
	"Garbage_container",
	"Land_Misc_GContainer_Big",
	"Land_Misc_Garb_3_EP1",
	"Land_Misc_Garb_3_EP1",
	"Land_Misc_Garb_4_EP1",
	"Land_Misc_Garb_Square_EP1",
	"Land_popelnice",
	"Land_popelnice_2",
	"Land_cwa_Pneu",
	"Land_Pneu",
	"land_cwa_tires",
	"Land_tires_EP1",
	"Campfire_burning_F",
	"Land_Campfire_F",
	"FirePlace_burning_F",
	"Land_FirePlace_F",
	"Land_Campfire",
	"Land_Campfire_burning",
	"Fire",
	"cwa_Fire",
	"FireLit",
	"Land_Fire",
	"Land_Fire_burning",
	"Land_Fire_barrel",
	"ACE_envelope_big",
	"GRAD_envelope_gigant",
	"ACE_envelope_small",
	"GRAD_envelope_vehicle",
	"Land_Trench_01_forest_F",
	"Land_TrenchFrame_01_F",
	"Land_Trench_01_grass_F",
	"Fort_EnvelopeBig",
	"Fort_EnvelopeSmall",
	"Fort_EnvelopeBig_EP1",
	"Fort_EnvelopeSmall_EP1"
];
publicvariable "acpl_config_notabuilding";

acpl_config_buildings_inited = true;
publicvariable "acpl_config_buildings_inited";