/*
	By RomanPL79
	Version WIP 11-08-2017
	
	Skrypt pozwalający na przepakowywanie amunicji do kontatybilnych magazynków

*/

if (!isServer) exitwith {};

{
[_x,["ACPL44RepackScript","ACPL44 Repack Script"]] remoteExec ["createDiarySubject",0,true];
[_x,["acpl44repackscript", ["UWAGA!", "Jest to wersja skryptu WIP (Work In Progress) - oznacza to, że niektóre rodzaje uzbrojenia, amunicji, itd nie zostały jeszcze dodane oraz mogą występować większe lub mniejsze błędy.<br/>Na razie należy wystrzegać się/brakuje:<br/>-Przepakowywania amunicji przy zapełnionym lub prawie zapełnionym ekwipunku (może zjeść nowe magazynki).<br/>-Nie dodano jeszcze uzbrojenia radziackiego<br/>-Braki w uzbrojeniu amerykańskim (broń krótka, LKM)."]]] remoteExec ["createDiaryRecord",0,true];
[_x,["acpl44repackscript", ["ACPL44 Repack Script", "By RomanPL79<br/>Version WIP 11-08-2017<br/><br/>Skrypt napisany w celu umożliwienia przepakowywania amunicji o tym samym kalibrze między magazynkami na teatrze WW2.<br/><br/>JAK UŻYWAĆ:<br/>Gdy mamy w swoim wyposażeniu broń oraz magazynek na tą samą amunicje (np.: brytyjskie 303) w Self Interaction Menu pojawi się nam opcja 'Repack Mags'. Po najechaniu na nią powinna się nam wyświetlić nasza broń, a pod nią magazynek z którego będziemy czerpać amunicje. Po wybraniu magazynka niepasujący magazynek zniknie z naszego wyposażenia a zamiast niego pojawi się nowy - pasujący do naszej broni."]]] remoteExec ["createDiaryRecord",0,true];
} foreach allunits;

acpl_repack_nemu = ["acpl_repack_nemu", "Repack Mags", "", {}, {true}] call ace_interact_menu_fnc_createAction;

//9x19
acpl_repack_sten = ["acpl_repack_sten", "Sten", (getText (configFile >> 'CfgWeapons' >> "fow_w_sten_mk2" >> 'picture')), {}, {(primaryWeapon player == "fow_w_sten_mk2") OR (primaryWeapon player == "fow_w_sten_mk5")}] call ace_interact_menu_fnc_createAction;
acpl_repack_sten_mp40mag = ["acpl_repack_sten_mp40mag", "MP 40 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_32Rnd_9x19" >> 'picture')), {[[player,"LIB_32Rnd_9x19","fow_32Rnd_9x19_sten",32],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_32Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_sten_p08mag = ["acpl_repack_sten_p08mag", "P-08 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_9x19_P08" >> 'picture')), {[[player,"LIB_8Rnd_9x19_P08","fow_32Rnd_9x19_sten",32],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_8Rnd_9x19_P08" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_sten_p38mag = ["acpl_repack_sten_p38mag", "P38 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_9x19" >> 'picture')), {[[player,"LIB_8Rnd_9x19","fow_32Rnd_9x19_sten",32],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_8Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_P08 = ["acpl_repack_P08", "P08", (getText (configFile >> 'CfgWeapons' >> "LIB_P08" >> 'picture')), {}, {(handgunWeapon player == "LIB_P08")}] call ace_interact_menu_fnc_createAction;
acpl_repack_P08_stenmag = ["acpl_repack_P08_stenmag", "32Rnd 9x19", (getText (configFile >> 'CfgMagazines' >> "fow_32Rnd_9x19_sten" >> 'picture')), {[[player,"fow_32Rnd_9x19_sten","LIB_8Rnd_9x19_P08",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"fow_32Rnd_9x19_sten" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_P08_mp40mag = ["acpl_repack_P08_mp40mag", "MP 40 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_32Rnd_9x19" >> 'picture')), {[[player,"LIB_32Rnd_9x19","LIB_8Rnd_9x19_P08",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"LIB_32Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_P08_p38mag = ["acpl_repack_P08_p38mag", "P38 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_9x19" >> 'picture')), {[[player,"LIB_8Rnd_9x19","LIB_8Rnd_9x19_P08",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"LIB_8Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_MP40 = ["acpl_repack_MP40", "MP40", (getText (configFile >> 'CfgWeapons' >> "LIB_MP40" >> 'picture')), {}, {(primaryWeapon player == "fow_w_mp40") OR (primaryWeapon player == "LIB_MP40")}] call ace_interact_menu_fnc_createAction;
acpl_repack_MP40_stenmag = ["acpl_repack_MP40_stenmag", "32Rnd 9x19", (getText (configFile >> 'CfgMagazines' >> "fow_32Rnd_9x19_sten" >> 'picture')), {[[player,"fow_32Rnd_9x19_sten","LIB_32Rnd_9x19",32],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"fow_32Rnd_9x19_sten" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MP40_p08mag = ["acpl_repack_MP40_p08mag", "P-08 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_9x19_P08" >> 'picture')), {[[player,"LIB_8Rnd_9x19_P08","LIB_32Rnd_9x19",32],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"LIB_8Rnd_9x19_P08" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MP40_p38mag = ["acpl_repack_MP40_p38mag", "P38 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_9x19" >> 'picture')), {[[player,"LIB_8Rnd_9x19","LIB_32Rnd_9x19",32],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"LIB_8Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_P38 = ["acpl_repack_P38", "P38", (getText (configFile >> 'CfgWeapons' >> "LIB_P38" >> 'picture')), {}, {(handgunWeapon player == "LIB_P38")}] call ace_interact_menu_fnc_createAction;
acpl_repack_P38_stenmag = ["acpl_repack_P38_stenmag", "32Rnd 9x19", (getText (configFile >> 'CfgMagazines' >> "fow_32Rnd_9x19_sten" >> 'picture')), {[[player,"fow_32Rnd_9x19_sten","LIB_8Rnd_9x19",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"fow_32Rnd_9x19_sten" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_P38_mp40mag = ["acpl_repack_P38_mp40mag", "MP 40 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_32Rnd_9x19" >> 'picture')), {[[player,"LIB_32Rnd_9x19","LIB_8Rnd_9x19",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"LIB_32Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_P38_p08mag = ["acpl_repack_P38_p08mag", "P08 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_9x19_P08" >> 'picture')), {[[player,"LIB_8Rnd_9x19_P08","LIB_8Rnd_9x19",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked"}, {"LIB_8Rnd_9x19" in (magazines player)}] call ace_interact_menu_fnc_createAction;

//.303
acpl_repack_bren = ["acpl_repack_bren", "Bren", (getText (configFile >> 'CfgWeapons' >> "fow_w_bren" >> 'picture')), {}, {(primaryWeapon player == "fow_w_bren")}] call ace_interact_menu_fnc_createAction;
acpl_repack_bren_lee = ["acpl_repack_bren_lee", "10Rnd 303 LeeEnfield", (getText (configFile >> 'CfgMagazines' >> "fow_10Rnd_303" >> 'picture')), {[[player,"fow_10Rnd_303","fow_30Rnd_303_bren",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_10Rnd_303" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_lee = ["acpl_repack_lee", "Lee Enfield", (getText (configFile >> 'CfgWeapons' >> "fow_w_leeenfield_no4mk1" >> 'picture')), {}, {(primaryWeapon player == "fow_w_leeenfield_no4mk1") OR (primaryWeapon player == "fow_w_leeenfield_no4mk1_redwood")}] call ace_interact_menu_fnc_createAction;
acpl_repack_lee_bren = ["acpl_repack_bren_lee", "30Rnd 303 Bren", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_303_bren" >> 'picture')), {[[player,"fow_30Rnd_303_bren","fow_10Rnd_303",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_303_bren" in (magazines player)}] call ace_interact_menu_fnc_createAction;

//.45
acpl_repack_M1A1T = ["acpl_repack_M1A1T", "M1A1 Thompson", (getText (configFile >> 'CfgWeapons' >> "LIB_M1A1_Thompson" >> 'picture')), {}, {(primaryWeapon player == "fow_w_m1a1_thompson") OR (primaryWeapon player == "LIB_M1A1_Thompson") OR (primaryWeapon player == "LIB_M1928A1_Thompson") OR (primaryWeapon player == "LIB_M1928_Thompson") OR (primaryWeapon player == "LIB_M1928_Thompson_d")}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1A1T_M3GG = ["acpl_repack_M1A1T_M3GG", "30Rnd .45 ACP", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_45acp" >> 'picture')), {[[player,"fow_30Rnd_45acp","LIB_30Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_45acp" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1A1T_M3GG_T = ["acpl_repack_M1A1T_M3GG_T", "30Rnd .45 ACP (T)", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_45acp_T" >> 'picture')), {[[player,"fow_30Rnd_45acp_T","LIB_30Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_45acp_T" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1A1T_50rnd = ["acpl_repack_M1A1T_50rnd", "50 .45ACP Round Drum mag", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_45ACP" >> 'picture')), {[[player,"LIB_50Rnd_45ACP","LIB_30Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1A1T_1911 = ["acpl_repack_M1A1T_1911", "Colt M1911 Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_7Rnd_45ACP" >> 'picture')), {[[player,"LIB_7Rnd_45ACP","LIB_30Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_7Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1A1T_1911b = ["acpl_repack_M1A1T_1911b", "7Rnd .45 APC", (getText (configFile >> 'CfgMagazines' >> "fow_7Rnd_45acp" >> 'picture')), {[[player,"fow_7Rnd_45acp","LIB_30Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_7Rnd_45acp" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_M1928 = ["acpl_repack_M1928", "M1928 Thompson (Drum)", (getText (configFile >> 'CfgWeapons' >> "LIB_M1928_Thompson_d" >> 'picture')), {}, {(primaryWeapon player == "LIB_M1928_Thompson") OR (primaryWeapon player == "LIB_M1928_Thompson_d")}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1928_30rnd = ["acpl_repack_M1928_30rnd", "30 .45ACP Rounds Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_30Rnd_45ACP" >> 'picture')), {[[player,"LIB_30Rnd_45ACP","LIB_50Rnd_45ACP",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_30Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1928_M3GG = ["acpl_repack_M1928_M3GG", "30Rnd .45 ACP", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_45acp" >> 'picture')), {[[player,"fow_30Rnd_45acp","LIB_50Rnd_45ACP",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_45acp" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1928_M3GG_T = ["acpl_repack_M1928_M3GG_T", "30Rnd .45 ACP (T)", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_45acp_T" >> 'picture')), {[[player,"fow_30Rnd_45acp_T","LIB_50Rnd_45ACP",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_45acp_T" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1928_1911 = ["acpl_repack_M1928_1911", "Colt M1911 Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_7Rnd_45ACP" >> 'picture')), {[[player,"LIB_7Rnd_45ACP","LIB_50Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_7Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1928_1911b = ["acpl_repack_M1928_1911b", "7Rnd .45 APC", (getText (configFile >> 'CfgMagazines' >> "fow_7Rnd_45acp" >> 'picture')), {[[player,"fow_7Rnd_45acp","LIB_50Rnd_45ACP",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_7Rnd_45acp" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_M3GG = ["acpl_repack_M3GG", "M3 GreaseGun", (getText (configFile >> 'CfgWeapons' >> "fow_w_m3" >> 'picture')), {}, {(primaryWeapon player == "fow_w_m3")}] call ace_interact_menu_fnc_createAction;
acpl_repack_M3GG_50rnd = ["acpl_repack_M3GG_50rnd", "50 .45ACP Round Drum mag", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_45ACP" >> 'picture')), {[[player,"LIB_50Rnd_45ACP","fow_30Rnd_45acp",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M3GG_1911 = ["acpl_repack_M3GG_1911", "Colt M1911 Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_7Rnd_45ACP" >> 'picture')), {[[player,"LIB_7Rnd_45ACP","fow_30Rnd_45acp",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_7Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M3GG_1911b = ["acpl_repack_M3GG_1911b", "7Rnd .45 APC", (getText (configFile >> 'CfgMagazines' >> "fow_7Rnd_45acp" >> 'picture')), {[[player,"fow_7Rnd_45acp","fow_30Rnd_45acp",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_7Rnd_45acp" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M3GG_30rnd = ["acpl_repack_M3GG_30rnd", "30 .45ACP Rounds Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_30Rnd_45ACP" >> 'picture')), {[[player,"LIB_30Rnd_45ACP","fow_30Rnd_45acp",30],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_30Rnd_45ACP" in (magazines player)}] call ace_interact_menu_fnc_createAction;

//30-06
acpl_repack_M1Garand = ["acpl_repack_M1Garand", "M1 Garand", (getText (configFile >> 'CfgWeapons' >> "fow_w_m1_garand" >> 'picture')), {}, {(primaryWeapon player == "fow_w_m1_garand") OR (primaryWeapon player == "LIB_M1_Garand")}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_SF = ["acpl_repack_M1Garand_SF", "M1903A4 Springfield Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_762x63" >> 'picture')), {[[player,"LIB_5Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_BAR = ["acpl_repack_M1Garand_BAR", "M1918A2 BAR Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_20Rnd_762x63" >> 'picture')), {[[player,"LIB_20Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_20Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_BARb = ["acpl_repack_M1Garand_BARb", "20Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_20Rnd_762x63" >> 'picture')), {[[player,"fow_20Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_20Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_2 = ["acpl_repack_M1Garand_2", "8Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_8Rnd_762x63" >> 'picture')), {[[player,"fow_8Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_8Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_M1919_30 = ["acpl_repack_M1Garand_M1919_30", "30Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_762x63" >> 'picture')), {[[player,"fow_30Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_M1919_50 = ["acpl_repack_M1Garand_M1919_50", "50Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_762x63" >> 'picture')), {[[player,"fow_50Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_M1919_100 = ["acpl_repack_M1Garand_M1919_100", "100Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_100Rnd_762x63" >> 'picture')), {[[player,"fow_100Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_100Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_M1919_50b = ["acpl_repack_M1Garand_M1919_50b", "50 rounds M1919 Belt", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_762x63" >> 'picture')), {[[player,"LIB_50Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1Garand_M1919_100b = ["acpl_repack_M1Garand_M1919_100b", "100 rounds M1919 Belt", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_762x63" >> 'picture')), {[[player,"LIB_100Rnd_762x63","LIB_8Rnd_762x63",8],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_M1904 = ["acpl_repack_M1904", "M1904A4 Springfield", (getText (configFile >> 'CfgWeapons' >> "LIB_M1903A3_Springfield" >> 'picture')), {}, {(primaryWeapon player == "LIB_M1903A3_Springfield") OR (primaryWeapon player == "LIB_M1903A4_Springfield")}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1Garand = ["acpl_repack_M1904_M1Garand", "M1 Garand Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_762x63" >> 'picture')), {[[player,"LIB_8Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_8Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_BAR = ["acpl_repack_M1904_BAR", "M1918A2 BAR Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_20Rnd_762x63" >> 'picture')), {[[player,"LIB_20Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_20Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_BARb = ["acpl_repack_M1904_BARb", "20Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_20Rnd_762x63" >> 'picture')), {[[player,"fow_20Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_20Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1Garandb = ["acpl_repack_M1904_M1Garandb", "8Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_8Rnd_762x63" >> 'picture')), {[[player,"fow_8Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_8Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1919_30 = ["acpl_repack_M1904_M1919_30", "30Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_762x63" >> 'picture')), {[[player,"fow_30Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1919_50 = ["acpl_repack_M1904_M1919_50", "50Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_762x63" >> 'picture')), {[[player,"fow_50Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1919_100 = ["acpl_repack_M1904_M1919_100", "100Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_100Rnd_762x63" >> 'picture')), {[[player,"fow_100Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_100Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1919_50b = ["acpl_repack_M1904_M1919_50b", "50 rounds M1919 Belt", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_762x63" >> 'picture')), {[[player,"LIB_50Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1904_M1919_100b = ["acpl_repack_M1904_M1919_100b", "100 rounds M1919 Belt", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_762x63" >> 'picture')), {[[player,"LIB_100Rnd_762x63","LIB_5Rnd_762x63",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_M1918 = ["acpl_repack_M1918", "M1918A2 BAR", (getText (configFile >> 'CfgWeapons' >> "LIB_M1918A2_BAR" >> 'picture')), {}, {(primaryWeapon player == "LIB_M1918A2_BAR") OR (primaryWeapon player == "fow_w_m1918a2") OR (primaryWeapon player == "fow_w_m1918a2_bak")}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1Garand = ["acpl_repack_M1918_M1Garand", "M1 Garand Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_8Rnd_762x63" >> 'picture')), {[[player,"LIB_8Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_8Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_SF = ["acpl_repack_M1918_SF", "M1903A4 Springfield Mag", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_762x63" >> 'picture')), {[[player,"LIB_5Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_BARb = ["acpl_repack_M1918_BARb", "20Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_20Rnd_762x63" >> 'picture')), {[[player,"fow_20Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_20Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1Garandb = ["acpl_repack_M1918_M1Garandb", "8Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_8Rnd_762x63" >> 'picture')), {[[player,"fow_8Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_8Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1919_30 = ["acpl_repack_M1918_M1919_30", "30Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_30Rnd_762x63" >> 'picture')), {[[player,"fow_30Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_30Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1919_50 = ["acpl_repack_M1918_M1919_50", "50Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_762x63" >> 'picture')), {[[player,"fow_50Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1919_100 = ["acpl_repack_M1918_M1919_100", "100Rnd 762x63", (getText (configFile >> 'CfgMagazines' >> "fow_100Rnd_762x63" >> 'picture')), {[[player,"fow_100Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_100Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1919_50b = ["acpl_repack_M1918_M1919_50b", "50 rounds M1919 Belt", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_762x63" >> 'picture')), {[[player,"LIB_50Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_M1918_M1919_100b = ["acpl_repack_M1918_M1919_100b", "100 rounds M1919 Belt", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_762x63" >> 'picture')), {[[player,"LIB_100Rnd_762x63","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_762x63" in (magazines player)}] call ace_interact_menu_fnc_createAction;

//7,92x57
acpl_repack_kar98k = ["acpl_repack_kar98k", "Kar98k", (getText (configFile >> 'CfgWeapons' >> "LIB_K98" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43") OR (primaryWeapon player == "fow_w_k98") OR (primaryWeapon player == "LIB_K98") OR (primaryWeapon player == "LIB_K98ZF39") OR (primaryWeapon player == "LIB_G3340")}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k_G43 = ["acpl_repack_kar98k_G43", "G43 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57" >> 'picture')), {[[player,"LIB_10Rnd_792x57","LIB_5Rnd_792x57",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k_MG42a = ["acpl_repack_kar98k_MG42a", "50Rnd 7.92x57", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_792x57" >> 'picture')), {[[player,"fow_50Rnd_792x57","LIB_5Rnd_792x57",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k_MG42b = ["acpl_repack_kar98k_MG42b", "100 Rnd Box (MG 34/ 42)", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_792x57" >> 'picture')), {[[player,"LIB_100Rnd_792x57","LIB_5Rnd_792x57",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k_MG42c = ["acpl_repack_kar98k_MG42c", "50 rounds Gurttrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57" >> 'picture')), {[[player,"LIB_50Rnd_792x57","LIB_5Rnd_792x57",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k_MG42d = ["acpl_repack_kar98k_MG42d", "75 rounds Patronentrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_75Rnd_792x57" >> 'picture')), {[[player,"LIB_75Rnd_792x57","LIB_5Rnd_792x57",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_75Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_kar98k2 = ["acpl_repack_kar98k2", "Kar98k (T)", (getText (configFile >> 'CfgWeapons' >> "LIB_K98" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43") OR (primaryWeapon player == "fow_w_k98") OR (primaryWeapon player == "LIB_K98") OR (primaryWeapon player == "LIB_K98ZF39") OR (primaryWeapon player == "LIB_G3340")}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k2_G43 = ["acpl_repack_kar98k2_G43", "10Rnd. G43 T", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57_T" >> 'picture')), {[[player,"LIB_10Rnd_792x57_T","LIB_5Rnd_792x57_t",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57_T" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k2_G432 = ["acpl_repack_kar98k2_G432", "10Rnd. G43 T(2)", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57_T2" >> 'picture')), {[[player,"LIB_10Rnd_792x57_T2","LIB_5Rnd_792x57_t",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57_T" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_kar98k3 = ["acpl_repack_kar98k3", "Kar98k (SmE)", (getText (configFile >> 'CfgWeapons' >> "LIB_K98" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43") OR (primaryWeapon player == "fow_w_k98") OR (primaryWeapon player == "LIB_K98") OR (primaryWeapon player == "LIB_K98ZF39") OR (primaryWeapon player == "LIB_G3340")}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k3_G43 = ["acpl_repack_kar98k3_G43", "10Rnd. G43 SmE", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57_sS" >> 'picture')), {[[player,"LIB_10Rnd_792x57_sS","LIB_5Rnd_792x57_sS",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57_sS" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k3_MG42 = ["acpl_repack_kar98k3_MG42", "50Rnd. MG42 SmE", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57_sS" >> 'picture')), {[[player,"LIB_50Rnd_792x57_sS","LIB_5Rnd_792x57_sS",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57_sS" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_kar98k4 = ["acpl_repack_kar98k4", "Kar98k (SMK)", (getText (configFile >> 'CfgWeapons' >> "LIB_K98" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43") OR (primaryWeapon player == "fow_w_k98") OR (primaryWeapon player == "LIB_K98") OR (primaryWeapon player == "LIB_K98ZF39") OR (primaryWeapon player == "LIB_G3340")}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k4_G43 = ["acpl_repack_kar98k4_G43", "10Rnd. G43 SMK", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57_SMK" >> 'picture')), {[[player,"LIB_10Rnd_792x57_SMK","LIB_5Rnd_792x57_SMK",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57_SMK" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_kar98k4_MG42 = ["acpl_repack_kar98k4_MG42", "50Rnd. MG42 SMK", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57_SMK" >> 'picture')), {[[player,"LIB_50Rnd_792x57_SMK","LIB_5Rnd_792x57_SMK",5],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57_SMK" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_G43 = ["acpl_repack_G43", "G43", (getText (configFile >> 'CfgWeapons' >> "LIB_G43" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43")}] call ace_interact_menu_fnc_createAction;
acpl_repack_G43_kar98k = ["acpl_repack_G43_kar98k", "Kar98k Clip", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57" >> 'picture')), {[[player,"LIB_5Rnd_792x57","LIB_10Rnd_792x57",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_G43_MG42a = ["acpl_repack_G43_MG42a", "50Rnd 7.92x57", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_792x57" >> 'picture')), {[[player,"fow_50Rnd_792x57","LIB_10Rnd_792x57",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_G43_MG42b = ["acpl_repack_G43_MG42b", "100 Rnd Box (MG 34/ 42)", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_792x57" >> 'picture')), {[[player,"LIB_100Rnd_792x57","LIB_10Rnd_792x57",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_G43_MG42c = ["acpl_repack_G43_MG42c", "50 rounds Gurttrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57" >> 'picture')), {[[player,"LIB_50Rnd_792x57","LIB_10Rnd_792x57",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_G43_MG42d = ["acpl_repack_G43_MG42d", "75 rounds Patronentrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_75Rnd_792x57" >> 'picture')), {[[player,"LIB_75Rnd_792x57","LIB_10Rnd_792x57",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_75Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_G432 = ["acpl_repack_G432", "G43 (T)", (getText (configFile >> 'CfgWeapons' >> "LIB_G43" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43")}] call ace_interact_menu_fnc_createAction;
acpl_repack_G432_kar98k = ["acpl_repack_G432_kar98k", "5Rnd. Kar98k T", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57_t" >> 'picture')), {[[player,"LIB_5Rnd_792x57_t","LIB_10Rnd_792x57_T",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57_t" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_G433 = ["acpl_repack_G433", "G43 (SmE)", (getText (configFile >> 'CfgWeapons' >> "LIB_G43" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43")}] call ace_interact_menu_fnc_createAction;
acpl_repack_G433_kar98k = ["acpl_repack_G432_kar98k", "5Rnd. Kar98k SmE", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57_sS" >> 'picture')), {[[player,"LIB_5Rnd_792x57_sS","LIB_10Rnd_792x57_sS",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57_sS" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_G433_MG42 = ["acpl_repack_G433_MG42", "50Rnd. MG42 SmE", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57_sS" >> 'picture')), {[[player,"LIB_50Rnd_792x57_sS","LIB_10Rnd_792x57_sS",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57_sS" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_G434 = ["acpl_repack_G434", "G43 (SMK)", (getText (configFile >> 'CfgWeapons' >> "LIB_G43" >> 'picture')), {}, {(primaryWeapon player == "LIB_G43")}] call ace_interact_menu_fnc_createAction;
acpl_repack_G434_kar98k = ["acpl_repack_G432_kar98k", "5Rnd. Kar98k SMK", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57_SMK" >> 'picture')), {[[player,"LIB_5Rnd_792x57_SMK","LIB_5Rnd_792x57_SMK",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57_SMK" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_G434_MG42 = ["acpl_repack_G434_MG42", "50Rnd. MG42 SMK", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57_SMK" >> 'picture')), {[[player,"LIB_50Rnd_792x57_SMK","LIB_5Rnd_792x57_SMK",10],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57_SMK" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_MG42 = ["acpl_repack_MG42", "MG42", (getText (configFile >> 'CfgWeapons' >> "LIB_MG42" >> 'picture')), {}, {(primaryWeapon player == "LIB_MG42") OR (primaryWeapon player == "LIB_MG34") OR (primaryWeapon player == "fow_w_mg42")}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG42_G43 = ["acpl_repack_MG42_G43", "G43 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57" >> 'picture')), {[[player,"LIB_10Rnd_792x57","LIB_50Rnd_792x57",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG42_kar98k = ["acpl_repack_MG42_kar98k", "Kar98k Clip", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57" >> 'picture')), {[[player,"LIB_5Rnd_792x57","LIB_50Rnd_792x57",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG42_MG42a = ["acpl_repack_MG42_MG42a", "50Rnd 7.92x57", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_792x57" >> 'picture')), {[[player,"fow_50Rnd_792x57","LIB_50Rnd_792x57",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG42_MG42b = ["acpl_repack_MG42_MG42b", "100 Rnd Box (MG 34/ 42)", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_792x57" >> 'picture')), {[[player,"LIB_100Rnd_792x57","LIB_50Rnd_792x57",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG42_MG42c = ["acpl_repack_MG42_MG42c", "75 rounds Patronentrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_75Rnd_792x57" >> 'picture')), {[[player,"LIB_75Rnd_792x57","LIB_50Rnd_792x57",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_75Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_MG422 = ["acpl_repack_MG422", "MG42 (100Rnd)", (getText (configFile >> 'CfgWeapons' >> "LIB_MG42" >> 'picture')), {}, {(primaryWeapon player == "LIB_MG42") OR (primaryWeapon player == "LIB_MG34") OR (primaryWeapon player == "fow_w_mg42")}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG422_G43 = ["acpl_repack_MG422_G43", "G43 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57" >> 'picture')), {[[player,"LIB_10Rnd_792x57","LIB_100Rnd_792x57",100],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG422_kar98k = ["acpl_repack_MG422_kar98k", "Kar98k Clip", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57" >> 'picture')), {[[player,"LIB_5Rnd_792x57","LIB_100Rnd_792x57",100],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG422_MG42a = ["acpl_repack_MG422_MG42a", "50Rnd 7.92x57", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_792x57" >> 'picture')), {[[player,"fow_50Rnd_792x57","LIB_100Rnd_792x57",100],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG422_MG42b = ["acpl_repack_MG422_MG42b", "50 rounds Gurttrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57" >> 'picture')), {[[player,"LIB_50Rnd_792x57","LIB_100Rnd_792x57",100],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG422_MG42c = ["acpl_repack_MG422_MG42c", "75 rounds Patronentrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_75Rnd_792x57" >> 'picture')), {[[player,"LIB_75Rnd_792x57","LIB_100Rnd_792x57",100],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_75Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_MG423 = ["acpl_repack_MG423", "MG42 (SmE)", (getText (configFile >> 'CfgWeapons' >> "LIB_MG42" >> 'picture')), {}, {(primaryWeapon player == "LIB_MG42") OR (primaryWeapon player == "LIB_MG34") OR (primaryWeapon player == "fow_w_mg42")}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG423_G43 = ["acpl_repack_MG423_G43", "10Rnd. G43 SmE", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57_sS" >> 'picture')), {[[player,"LIB_10Rnd_792x57_sS","LIB_50Rnd_792x57_sS",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57_sS" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG423_kar98k = ["acpl_repack_MG423_kar98k", "5Rnd. Kar98k SmE", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57_sS" >> 'picture')), {[[player,"LIB_5Rnd_792x57_sS","LIB_50Rnd_792x57_sS",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57_sS" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_MG424 = ["acpl_repack_MG424", "MG42 (SMK)", (getText (configFile >> 'CfgWeapons' >> "LIB_MG42" >> 'picture')), {}, {(primaryWeapon player == "LIB_MG42") OR (primaryWeapon player == "LIB_MG34") OR (primaryWeapon player == "fow_w_mg42")}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG424_kar98k = ["acpl_repack_MG424_kar98k", "5Rnd. Kar98k SMK", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57_SMK" >> 'picture')), {[[player,"LIB_5Rnd_792x57_SMK","LIB_50Rnd_792x57_SMK",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57_SMK" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG424_G43 = ["acpl_repack_MG424_G43", "50Rnd. MG42 SMK", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57_SMK" >> 'picture')), {[[player,"LIB_10Rnd_792x57_SMK","LIB_50Rnd_792x57_SMK",50],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57_SMK" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_MG34 = ["acpl_repack_MG34", "MG34 (PT)", (getText (configFile >> 'CfgWeapons' >> "LIB_MG34_PT" >> 'picture')), {}, {(primaryWeapon player == "LIB_MG34_PT")}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG34_G43 = ["acpl_repack_MG34_G43", "G43 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57" >> 'picture')), {[[player,"LIB_10Rnd_792x57","LIB_75Rnd_792x57",75],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG34_kar98k = ["acpl_repack_MG34_kar98k", "Kar98k Clip", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57" >> 'picture')), {[[player,"LIB_5Rnd_792x57","LIB_75Rnd_792x57",75],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG34_MG42a = ["acpl_repack_MG34_MG42a", "50Rnd 7.92x57", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_792x57" >> 'picture')), {[[player,"fow_50Rnd_792x57","LIB_75Rnd_792x57",75],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG34_MG42b = ["acpl_repack_MG34_MG42b", "100 Rnd Box (MG 34/ 42)", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_792x57" >> 'picture')), {[[player,"LIB_100Rnd_792x57","LIB_75Rnd_792x57",75],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_MG34_MG42c = ["acpl_repack_MG34_MG42c", "50 rounds Gurttrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57" >> 'picture')), {[[player,"LIB_50Rnd_792x57","LIB_75Rnd_792x57",75],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;

acpl_repack_wz28 = ["acpl_repack_wz28", "Wz.28 BAR", (getText (configFile >> 'CfgWeapons' >> "LIB_M1918A2_BAR" >> 'picture')), {}, {acpl_WZ28_Enabled AND ((primaryWeapon player == "LIB_M1918A2_BAR") OR (primaryWeapon player == "fow_w_m1918a2") OR (primaryWeapon player == "fow_w_m1918a2_bak"))}] call ace_interact_menu_fnc_createAction;
acpl_repack_wz28_G43 = ["acpl_repack_wz28_G43", "G43 Magazine", (getText (configFile >> 'CfgMagazines' >> "LIB_10Rnd_792x57" >> 'picture')), {[[player,"LIB_10Rnd_792x57","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_10Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_wz28_kar98k = ["acpl_repack_wz28_kar98k", "Kar98k Clip", (getText (configFile >> 'CfgMagazines' >> "LIB_5Rnd_792x57" >> 'picture')), {[[player,"LIB_5Rnd_792x57","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_5Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_wz28_MG42a = ["acpl_repack_wz28_MG42a", "50Rnd 7.92x57", (getText (configFile >> 'CfgMagazines' >> "fow_50Rnd_792x57" >> 'picture')), {[[player,"fow_50Rnd_792x57","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"fow_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_wz28_MG42b = ["acpl_repack_wz28_MG42b", "100 Rnd Box (MG 34/ 42)", (getText (configFile >> 'CfgMagazines' >> "LIB_100Rnd_792x57" >> 'picture')), {[[player,"LIB_100Rnd_792x57","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_100Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_wz28_MG42c = ["acpl_repack_wz28_MG42c", "50 rounds Gurttrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_50Rnd_792x57" >> 'picture')), {[[player,"LIB_50Rnd_792x57","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_50Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;
acpl_repack_wz28_MG42d = ["acpl_repack_wz28_MG42d", "75 rounds Patronentrommel", (getText (configFile >> 'CfgMagazines' >> "LIB_75Rnd_792x57" >> 'picture')), {[[player,"LIB_75Rnd_792x57","LIB_20Rnd_762x63",20],"acpl_fncs\IF44\acpl_repack.sqf"] remoteExec ["execVM", 2];hint "Magazine Repacked";}, {"LIB_75Rnd_792x57" in (magazines player)}] call ace_interact_menu_fnc_createAction;

{
	[[(_x), 1, ["ACE_SelfActions"], acpl_repack_nemu],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_sten],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_sten"], acpl_repack_sten_mp40mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_sten"], acpl_repack_sten_p08mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_sten"], acpl_repack_sten_p38mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_P08],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_P08"], acpl_repack_P08_stenmag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_P08"], acpl_repack_P08_mp40mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_P08"], acpl_repack_P08_p38mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_MP40],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MP40"], acpl_repack_MP40_stenmag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MP40"], acpl_repack_MP40_p08mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MP40"], acpl_repack_MP40_p38mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_P38],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_P38"], acpl_repack_P38_stenmag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_P38"], acpl_repack_P38_mp40mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_P38"], acpl_repack_P38_p08mag],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_bren],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_bren"], acpl_repack_bren_lee],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_lee],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_lee"], acpl_repack_lee_bren],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_M1A1T],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1A1T"], acpl_repack_M1A1T_M3GG],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1A1T"], acpl_repack_M1A1T_M3GG_T],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1A1T"], acpl_repack_M1A1T_50rnd],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1A1T"], acpl_repack_M1A1T_1911],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1A1T"], acpl_repack_M1A1T_1911b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_M1928],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1928"], acpl_repack_M1928_30rnd],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1928"], acpl_repack_M1928_M3GG],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1928"], acpl_repack_M1928_M3GG_T],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1928"], acpl_repack_M1928_1911],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1928"], acpl_repack_M1928_1911b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_M3GG],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M3GG"], acpl_repack_M3GG_30rnd],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M3GG"], acpl_repack_M3GG_1911],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M3GG"], acpl_repack_M3GG_1911b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M3GG"], acpl_repack_M3GG_50rnd],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_M1Garand],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_SF],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_BAR],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_BARb],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_2],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_M1919_30],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_M1919_50],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_M1919_100],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_M1919_50b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1Garand"], acpl_repack_M1Garand_M1919_100b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_M1904],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1Garand],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_BAR],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_BARb],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1Garandb],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1919_30],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1919_50],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1919_100],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1919_50b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1904"], acpl_repack_M1904_M1919_100b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_M1918],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1Garand],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_SF],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_BARb],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1Garandb],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1919_30],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1919_50],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1919_100],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1919_50b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_M1918"], acpl_repack_M1918_M1919_100b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k"], acpl_repack_kar98k_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k"], acpl_repack_kar98k_MG42a],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k"], acpl_repack_kar98k_MG42b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k"], acpl_repack_kar98k_MG42c],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k"], acpl_repack_kar98k_MG42d],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_kar98k2],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k2"], acpl_repack_kar98k2_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k2"], acpl_repack_kar98k2_G432],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_kar98k3],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k3"], acpl_repack_kar98k3_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k3"], acpl_repack_kar98k3_MG42],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_kar98k4],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k4"], acpl_repack_kar98k4_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_kar98k4"], acpl_repack_kar98k4_MG42],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G43"], acpl_repack_G43_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G43"], acpl_repack_G43_MG42a],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G43"], acpl_repack_G43_MG42b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G43"], acpl_repack_G43_MG42c],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G43"], acpl_repack_G43_MG42d],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_G432],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G432"], acpl_repack_G432_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_G433],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G433"], acpl_repack_G433_MG42],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G433"], acpl_repack_G433_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_G434],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G434"], acpl_repack_G434_MG42],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_G434"], acpl_repack_G434_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_MG42],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG42"], acpl_repack_MG42_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG42"], acpl_repack_MG42_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG42"], acpl_repack_MG42_MG42a],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG42"], acpl_repack_MG42_MG42b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG42"], acpl_repack_MG42_MG42c],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_MG422],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG422"], acpl_repack_MG422_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG422"], acpl_repack_MG422_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG422"], acpl_repack_MG422_MG42a],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG422"], acpl_repack_MG422_MG42b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG422"], acpl_repack_MG422_MG42c],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_MG423],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG423"], acpl_repack_MG423_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG423"], acpl_repack_MG423_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_MG424],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG424"], acpl_repack_MG424_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG424"], acpl_repack_MG424_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_MG34],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG34"], acpl_repack_MG34_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG34"], acpl_repack_MG34_MG42a],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG34"], acpl_repack_MG34_MG42b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG34"], acpl_repack_MG34_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_MG34"], acpl_repack_MG34_MG42c],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu"], acpl_repack_wz28],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_wz28"], acpl_repack_wz28_G43],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_wz28"], acpl_repack_wz28_MG42a],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_wz28"], acpl_repack_wz28_MG42b],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_wz28"], acpl_repack_wz28_MG42c],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_wz28"], acpl_repack_wz28_MG42d],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
	[[(_x), 1, ["ACE_SelfActions", "acpl_repack_nemu","acpl_repack_wz28"], acpl_repack_wz28_kar98k],ace_interact_menu_fnc_addActionToObject] remoteExec ["call"];
} foreach allunits;